apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/name: kafka
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/name: kafka
  ports:
    - name: tcp-client
      protocol: TCP
      port: 9092
      targetPort: kafka-client
